logging:
  level:
    com.user.mvc: INFO

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schema_name
    username: root
    password: Museyib007
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
